#!/usr/bin/env python3
"""Writes RAMB18E2.v and RAMB36E2.v: compact cycle models of the UltraScale+ block RAMs in true dual
port mode at the full width (READ_WIDTH = WRITE_WIDTH = 18 or 36), as Vivado infers them for RTL
memories and xpm_memory.  Other widths, cascade, ECC and INDEPENDENT clocks stop at elaboration.

Checked against Vivado 2024.2's unisims by test/netdiff (cycle by cycle, X bits of the reference
not compared).  Collision behaviour with CLOCK_DOMAINS "COMMON", as the unisim gives it:
  * a port reading the address the other port writes in the same cycle gets the old word;
  * WRITE_FIRST returns the merged new word on the writing port, READ_FIRST the old word,
    NO_CHANGE keeps the output;
  * both ports writing the same address: port A's bytes win (the unisim also flags the outputs X).
"""
from pathlib import Path

HDR = '''`timescale 1 ps / 1 ps
// {name}: generated by gen_ramb.py (see there for what is modelled and how it was checked).
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off UNUSEDPARAM */
'''


def model(name, dw, pw, aw, ninit, ninitp, ports36):
    W = dw + pw; nb = pw; lo = aw - 10
    p = [f'  parameter CASCADE_ORDER_A = "NONE",', f'  parameter CASCADE_ORDER_B = "NONE",',
         f'  parameter CLOCK_DOMAINS = "INDEPENDENT",', f'  parameter integer DOA_REG = 1,', f'  parameter integer DOB_REG = 1,',
         f'  parameter ENADDRENA = "FALSE",', f'  parameter ENADDRENB = "FALSE",']
    if ports36:
        p += ['  parameter EN_ECC_PIPE = "FALSE",', '  parameter EN_ECC_READ = "FALSE",', '  parameter EN_ECC_WRITE = "FALSE",']
    p += [f'  parameter [255:0] INIT_{i:02X} = 256\'h0,' for i in range(ninit)]
    p += [f'  parameter [255:0] INITP_{i:02X} = 256\'h0,' for i in range(ninitp)]
    p += [f'  parameter [{W - 1}:0] INIT_A = {W}\'h0,', f'  parameter [{W - 1}:0] INIT_B = {W}\'h0,', '  parameter INIT_FILE = "NONE",']
    p += [f'  parameter [0:0] IS_{n}_INVERTED = 1\'b0,' for n in
          ('CLKARDCLK', 'CLKBWRCLK', 'ENARDEN', 'ENBWREN', 'RSTRAMARSTRAM', 'RSTRAMB', 'RSTREGARSTREG', 'RSTREGB')]
    p += ['  parameter RDADDRCHANGEA = "FALSE",', '  parameter RDADDRCHANGEB = "FALSE",',
          '  parameter integer READ_WIDTH_A = 0,', '  parameter integer READ_WIDTH_B = 0,',
          '  parameter RSTREG_PRIORITY_A = "RSTREG",', '  parameter RSTREG_PRIORITY_B = "RSTREG",',
          '  parameter SIM_COLLISION_CHECK = "ALL",', '  parameter SLEEP_ASYNC = "FALSE",',
          f'  parameter [{W - 1}:0] SRVAL_A = {W}\'h0,', f'  parameter [{W - 1}:0] SRVAL_B = {W}\'h0,',
          '  parameter WRITE_MODE_A = "NO_CHANGE",', '  parameter WRITE_MODE_B = "NO_CHANGE",',
          '  parameter integer WRITE_WIDTH_A = 0,', '  parameter integer WRITE_WIDTH_B = 0']
    o = [f'  output [{dw - 1}:0] CASDOUTA,', f'  output [{dw - 1}:0] CASDOUTB,', f'  output [{pw - 1}:0] CASDOUTPA,',
         f'  output [{pw - 1}:0] CASDOUTPB,']
    if ports36:
        o += ['  output CASOUTDBITERR,', '  output CASOUTSBITERR,', '  output DBITERR,']
    o += [f'  output [{dw - 1}:0] DOUTADOUT,', f'  output [{dw - 1}:0] DOUTBDOUT,', f'  output [{pw - 1}:0] DOUTPADOUTP,',
          f'  output [{pw - 1}:0] DOUTPBDOUTP,']
    if ports36:
        o += ['  output [7:0] ECCPARITY,', '  output [8:0] RDADDRECC,', '  output SBITERR,']
    i = [f'  input [{aw - 1}:0] ADDRARDADDR,', f'  input [{aw - 1}:0] ADDRBWRADDR,', '  input ADDRENA,', '  input ADDRENB,',
         '  input CASDIMUXA,', '  input CASDIMUXB,', f'  input [{dw - 1}:0] CASDINA,', f'  input [{dw - 1}:0] CASDINB,',
         f'  input [{pw - 1}:0] CASDINPA,', f'  input [{pw - 1}:0] CASDINPB,', '  input CASDOMUXA,', '  input CASDOMUXB,',
         '  input CASDOMUXEN_A,', '  input CASDOMUXEN_B,']
    if ports36:
        i += ['  input CASINDBITERR,', '  input CASINSBITERR,']
    i += ['  input CASOREGIMUXA,', '  input CASOREGIMUXB,', '  input CASOREGIMUXEN_A,', '  input CASOREGIMUXEN_B,',
          '  input CLKARDCLK,', '  input CLKBWRCLK,', f'  input [{dw - 1}:0] DINADIN,', f'  input [{dw - 1}:0] DINBDIN,',
          f'  input [{pw - 1}:0] DINPADINP,', f'  input [{pw - 1}:0] DINPBDINP,']
    if ports36:
        i += ['  input ECCPIPECE,']
    i += ['  input ENARDEN,', '  input ENBWREN,']
    if ports36:
        i += ['  input INJECTDBITERR,', '  input INJECTSBITERR,']
    i += ['  input REGCEAREGCE,', '  input REGCEB,', '  input RSTRAMARSTRAM,', '  input RSTRAMB,', '  input RSTREGARSTREG,',
          '  input RSTREGB,', '  input SLEEP,', f'  input [{nb - 1}:0] WEA,', f'  input [{2 * nb - 1}:0] WEBWE']
    body = f'''
  initial begin
    if (READ_WIDTH_A != {W} || READ_WIDTH_B != {W} || WRITE_WIDTH_A != {W} || WRITE_WIDTH_B != {W})
      $fatal(1, "{name} %m: only READ_WIDTH = WRITE_WIDTH = {W} is modelled");
    if (CASCADE_ORDER_A != "NONE" || CASCADE_ORDER_B != "NONE" || CLOCK_DOMAINS != "COMMON" || INIT_FILE != "NONE")
      $fatal(1, "{name} %m: cascade, INDEPENDENT clocks and INIT_FILE are not modelled");
{'' if not ports36 else '''    if (EN_ECC_READ != "FALSE" || EN_ECC_WRITE != "FALSE")
      $fatal(1, "RAMB36E2 %m: ECC is not modelled");
'''}  end

  // {1 << 10} words of {dw} data + {pw} parity bits; word w is INIT bits [{dw}w+{dw - 1}:{dw}w], INITP bits [{pw}w+{pw - 1}:{pw}w]
  reg [{W - 1}:0] mem [0:1023];
  wire [{256 * ninit - 1}:0] init = {{{', '.join(f'INIT_{k:02X}' for k in reversed(range(ninit)))}}};
  wire [{256 * ninitp - 1}:0] initp = {{{', '.join(f'INITP_{k:02X}' for k in reversed(range(ninitp)))}}};
  integer k;
  initial for (k = 0; k < 1024; k = k + 1) mem[k] = {{initp[{pw}*k +: {pw}], init[{dw}*k +: {dw}]}};

  function automatic [{W - 1}:0] bytes(input [{nb - 1}:0] we);   // lane i: data [8i+7:8i] and parity bit i
    integer b;
    bytes = 0;
    for (b = 0; b < {nb}; b = b + 1) if (we[b]) begin bytes[8 * b +: 8] = 8'hff; bytes[{dw} + b] = 1'b1; end
  endfunction

  wire en_a = ENARDEN ^ IS_ENARDEN_INVERTED, en_b = ENBWREN ^ IS_ENBWREN_INVERTED;
  wire rstram_a = RSTRAMARSTRAM ^ IS_RSTRAMARSTRAM_INVERTED, rstram_b = RSTRAMB ^ IS_RSTRAMB_INVERTED;
  wire rstreg_a = RSTREGARSTREG ^ IS_RSTREGARSTREG_INVERTED, rstreg_b = RSTREGB ^ IS_RSTREGB_INVERTED;
  wire [9:0] ad_a = ADDRARDADDR[{aw - 1}:{lo}], ad_b = ADDRBWRADDR[{aw - 1}:{lo}];
  wire [{W - 1}:0] m_a = en_a ? bytes(WEA) : {W}'h0, m_b = en_b ? bytes(WEBWE[{nb - 1}:0]) : {W}'h0;
  wire [{W - 1}:0] d_a = {{DINPADINP, DINADIN}}, d_b = {{DINPBDINP, DINBDIN}};
  wire [{W - 1}:0] old_a = mem[ad_a], old_b = mem[ad_b];
  wire [{W - 1}:0] new_a = d_a & m_a | old_a & ~m_a, new_b = d_b & m_b | old_b & ~m_b;
  wire both = |m_a && |m_b && ad_a == ad_b;                     // port A's bytes win
  reg [{W - 1}:0] lat_a = INIT_A, lat_b = INIT_B, reg_a = INIT_A, reg_b = INIT_B;

  always @(posedge CLKARDCLK) begin
    if (en_a) begin
      if (rstram_a) lat_a <= SRVAL_A;
      else if (!(|m_a)) lat_a <= old_a;
      else if (WRITE_MODE_A == "WRITE_FIRST") lat_a <= new_a;
      else if (WRITE_MODE_A == "READ_FIRST") lat_a <= old_a;
    end
    if (rstreg_a && (RSTREG_PRIORITY_A == "RSTREG" || REGCEAREGCE)) reg_a <= SRVAL_A;
    else if (REGCEAREGCE) reg_a <= lat_a;
    if (en_b) begin
      if (rstram_b) lat_b <= SRVAL_B;
      else if (!(|m_b)) lat_b <= old_b;
      else if (WRITE_MODE_B == "WRITE_FIRST") lat_b <= both ? new_a & m_a | new_b & ~m_a : new_b;
      else if (WRITE_MODE_B == "READ_FIRST") lat_b <= old_b;
    end
    if (rstreg_b && (RSTREG_PRIORITY_B == "RSTREG" || REGCEB)) reg_b <= SRVAL_B;
    else if (REGCEB) reg_b <= lat_b;
    if (|m_b) mem[ad_b] <= both ? new_a & m_a | new_b & ~m_a : new_b;
    if (|m_a && !both) mem[ad_a] <= new_a;
  end

  wire [{W - 1}:0] q_a = DOA_REG ? reg_a : lat_a, q_b = DOB_REG ? reg_b : lat_b;
  assign {{DOUTPADOUTP, DOUTADOUT}} = q_a;
  assign {{DOUTPBDOUTP, DOUTBDOUT}} = q_b;
  assign {{CASDOUTPA, CASDOUTA}} = q_a;
  assign {{CASDOUTPB, CASDOUTB}} = q_b;
'''
    if ports36:
        body += '''  assign CASOUTDBITERR = 1'b0; assign CASOUTSBITERR = 1'b0; assign DBITERR = 1'b0; assign SBITERR = 1'b0;
  assign ECCPARITY = 8'h0; assign RDADDRECC = 9'h0;
'''
    return (HDR.format(name=name) + f'module {name} #(\n' + '\n'.join(p) + '\n)(\n' + '\n'.join(o + i) + '\n);\n' + body +
            'endmodule\n/* verilator lint_on UNUSEDPARAM */\n/* verilator lint_on UNUSEDSIGNAL */\n')


here = Path(__file__).resolve().parent
(here / 'RAMB18E2.v').write_text(model('RAMB18E2', 16, 2, 14, 64, 8, False))
(here / 'RAMB36E2.v').write_text(model('RAMB36E2', 32, 4, 15, 128, 16, True))
