`timescale 1 ps / 1 ps
// RAMB36E2: generated by gen_ramb.py (see there for what is modelled and how it was checked).
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off UNUSEDPARAM */
module RAMB36E2 #(
  parameter CASCADE_ORDER_A = "NONE",
  parameter CASCADE_ORDER_B = "NONE",
  parameter CLOCK_DOMAINS = "INDEPENDENT",
  parameter integer DOA_REG = 1,
  parameter integer DOB_REG = 1,
  parameter ENADDRENA = "FALSE",
  parameter ENADDRENB = "FALSE",
  parameter EN_ECC_PIPE = "FALSE",
  parameter EN_ECC_READ = "FALSE",
  parameter EN_ECC_WRITE = "FALSE",
  parameter [255:0] INIT_00 = 256'h0,
  parameter [255:0] INIT_01 = 256'h0,
  parameter [255:0] INIT_02 = 256'h0,
  parameter [255:0] INIT_03 = 256'h0,
  parameter [255:0] INIT_04 = 256'h0,
  parameter [255:0] INIT_05 = 256'h0,
  parameter [255:0] INIT_06 = 256'h0,
  parameter [255:0] INIT_07 = 256'h0,
  parameter [255:0] INIT_08 = 256'h0,
  parameter [255:0] INIT_09 = 256'h0,
  parameter [255:0] INIT_0A = 256'h0,
  parameter [255:0] INIT_0B = 256'h0,
  parameter [255:0] INIT_0C = 256'h0,
  parameter [255:0] INIT_0D = 256'h0,
  parameter [255:0] INIT_0E = 256'h0,
  parameter [255:0] INIT_0F = 256'h0,
  parameter [255:0] INIT_10 = 256'h0,
  parameter [255:0] INIT_11 = 256'h0,
  parameter [255:0] INIT_12 = 256'h0,
  parameter [255:0] INIT_13 = 256'h0,
  parameter [255:0] INIT_14 = 256'h0,
  parameter [255:0] INIT_15 = 256'h0,
  parameter [255:0] INIT_16 = 256'h0,
  parameter [255:0] INIT_17 = 256'h0,
  parameter [255:0] INIT_18 = 256'h0,
  parameter [255:0] INIT_19 = 256'h0,
  parameter [255:0] INIT_1A = 256'h0,
  parameter [255:0] INIT_1B = 256'h0,
  parameter [255:0] INIT_1C = 256'h0,
  parameter [255:0] INIT_1D = 256'h0,
  parameter [255:0] INIT_1E = 256'h0,
  parameter [255:0] INIT_1F = 256'h0,
  parameter [255:0] INIT_20 = 256'h0,
  parameter [255:0] INIT_21 = 256'h0,
  parameter [255:0] INIT_22 = 256'h0,
  parameter [255:0] INIT_23 = 256'h0,
  parameter [255:0] INIT_24 = 256'h0,
  parameter [255:0] INIT_25 = 256'h0,
  parameter [255:0] INIT_26 = 256'h0,
  parameter [255:0] INIT_27 = 256'h0,
  parameter [255:0] INIT_28 = 256'h0,
  parameter [255:0] INIT_29 = 256'h0,
  parameter [255:0] INIT_2A = 256'h0,
  parameter [255:0] INIT_2B = 256'h0,
  parameter [255:0] INIT_2C = 256'h0,
  parameter [255:0] INIT_2D = 256'h0,
  parameter [255:0] INIT_2E = 256'h0,
  parameter [255:0] INIT_2F = 256'h0,
  parameter [255:0] INIT_30 = 256'h0,
  parameter [255:0] INIT_31 = 256'h0,
  parameter [255:0] INIT_32 = 256'h0,
  parameter [255:0] INIT_33 = 256'h0,
  parameter [255:0] INIT_34 = 256'h0,
  parameter [255:0] INIT_35 = 256'h0,
  parameter [255:0] INIT_36 = 256'h0,
  parameter [255:0] INIT_37 = 256'h0,
  parameter [255:0] INIT_38 = 256'h0,
  parameter [255:0] INIT_39 = 256'h0,
  parameter [255:0] INIT_3A = 256'h0,
  parameter [255:0] INIT_3B = 256'h0,
  parameter [255:0] INIT_3C = 256'h0,
  parameter [255:0] INIT_3D = 256'h0,
  parameter [255:0] INIT_3E = 256'h0,
  parameter [255:0] INIT_3F = 256'h0,
  parameter [255:0] INIT_40 = 256'h0,
  parameter [255:0] INIT_41 = 256'h0,
  parameter [255:0] INIT_42 = 256'h0,
  parameter [255:0] INIT_43 = 256'h0,
  parameter [255:0] INIT_44 = 256'h0,
  parameter [255:0] INIT_45 = 256'h0,
  parameter [255:0] INIT_46 = 256'h0,
  parameter [255:0] INIT_47 = 256'h0,
  parameter [255:0] INIT_48 = 256'h0,
  parameter [255:0] INIT_49 = 256'h0,
  parameter [255:0] INIT_4A = 256'h0,
  parameter [255:0] INIT_4B = 256'h0,
  parameter [255:0] INIT_4C = 256'h0,
  parameter [255:0] INIT_4D = 256'h0,
  parameter [255:0] INIT_4E = 256'h0,
  parameter [255:0] INIT_4F = 256'h0,
  parameter [255:0] INIT_50 = 256'h0,
  parameter [255:0] INIT_51 = 256'h0,
  parameter [255:0] INIT_52 = 256'h0,
  parameter [255:0] INIT_53 = 256'h0,
  parameter [255:0] INIT_54 = 256'h0,
  parameter [255:0] INIT_55 = 256'h0,
  parameter [255:0] INIT_56 = 256'h0,
  parameter [255:0] INIT_57 = 256'h0,
  parameter [255:0] INIT_58 = 256'h0,
  parameter [255:0] INIT_59 = 256'h0,
  parameter [255:0] INIT_5A = 256'h0,
  parameter [255:0] INIT_5B = 256'h0,
  parameter [255:0] INIT_5C = 256'h0,
  parameter [255:0] INIT_5D = 256'h0,
  parameter [255:0] INIT_5E = 256'h0,
  parameter [255:0] INIT_5F = 256'h0,
  parameter [255:0] INIT_60 = 256'h0,
  parameter [255:0] INIT_61 = 256'h0,
  parameter [255:0] INIT_62 = 256'h0,
  parameter [255:0] INIT_63 = 256'h0,
  parameter [255:0] INIT_64 = 256'h0,
  parameter [255:0] INIT_65 = 256'h0,
  parameter [255:0] INIT_66 = 256'h0,
  parameter [255:0] INIT_67 = 256'h0,
  parameter [255:0] INIT_68 = 256'h0,
  parameter [255:0] INIT_69 = 256'h0,
  parameter [255:0] INIT_6A = 256'h0,
  parameter [255:0] INIT_6B = 256'h0,
  parameter [255:0] INIT_6C = 256'h0,
  parameter [255:0] INIT_6D = 256'h0,
  parameter [255:0] INIT_6E = 256'h0,
  parameter [255:0] INIT_6F = 256'h0,
  parameter [255:0] INIT_70 = 256'h0,
  parameter [255:0] INIT_71 = 256'h0,
  parameter [255:0] INIT_72 = 256'h0,
  parameter [255:0] INIT_73 = 256'h0,
  parameter [255:0] INIT_74 = 256'h0,
  parameter [255:0] INIT_75 = 256'h0,
  parameter [255:0] INIT_76 = 256'h0,
  parameter [255:0] INIT_77 = 256'h0,
  parameter [255:0] INIT_78 = 256'h0,
  parameter [255:0] INIT_79 = 256'h0,
  parameter [255:0] INIT_7A = 256'h0,
  parameter [255:0] INIT_7B = 256'h0,
  parameter [255:0] INIT_7C = 256'h0,
  parameter [255:0] INIT_7D = 256'h0,
  parameter [255:0] INIT_7E = 256'h0,
  parameter [255:0] INIT_7F = 256'h0,
  parameter [255:0] INITP_00 = 256'h0,
  parameter [255:0] INITP_01 = 256'h0,
  parameter [255:0] INITP_02 = 256'h0,
  parameter [255:0] INITP_03 = 256'h0,
  parameter [255:0] INITP_04 = 256'h0,
  parameter [255:0] INITP_05 = 256'h0,
  parameter [255:0] INITP_06 = 256'h0,
  parameter [255:0] INITP_07 = 256'h0,
  parameter [255:0] INITP_08 = 256'h0,
  parameter [255:0] INITP_09 = 256'h0,
  parameter [255:0] INITP_0A = 256'h0,
  parameter [255:0] INITP_0B = 256'h0,
  parameter [255:0] INITP_0C = 256'h0,
  parameter [255:0] INITP_0D = 256'h0,
  parameter [255:0] INITP_0E = 256'h0,
  parameter [255:0] INITP_0F = 256'h0,
  parameter [35:0] INIT_A = 36'h0,
  parameter [35:0] INIT_B = 36'h0,
  parameter INIT_FILE = "NONE",
  parameter [0:0] IS_CLKARDCLK_INVERTED = 1'b0,
  parameter [0:0] IS_CLKBWRCLK_INVERTED = 1'b0,
  parameter [0:0] IS_ENARDEN_INVERTED = 1'b0,
  parameter [0:0] IS_ENBWREN_INVERTED = 1'b0,
  parameter [0:0] IS_RSTRAMARSTRAM_INVERTED = 1'b0,
  parameter [0:0] IS_RSTRAMB_INVERTED = 1'b0,
  parameter [0:0] IS_RSTREGARSTREG_INVERTED = 1'b0,
  parameter [0:0] IS_RSTREGB_INVERTED = 1'b0,
  parameter RDADDRCHANGEA = "FALSE",
  parameter RDADDRCHANGEB = "FALSE",
  parameter integer READ_WIDTH_A = 0,
  parameter integer READ_WIDTH_B = 0,
  parameter RSTREG_PRIORITY_A = "RSTREG",
  parameter RSTREG_PRIORITY_B = "RSTREG",
  parameter SIM_COLLISION_CHECK = "ALL",
  parameter SLEEP_ASYNC = "FALSE",
  parameter [35:0] SRVAL_A = 36'h0,
  parameter [35:0] SRVAL_B = 36'h0,
  parameter WRITE_MODE_A = "NO_CHANGE",
  parameter WRITE_MODE_B = "NO_CHANGE",
  parameter integer WRITE_WIDTH_A = 0,
  parameter integer WRITE_WIDTH_B = 0
)(
  output [31:0] CASDOUTA,
  output [31:0] CASDOUTB,
  output [3:0] CASDOUTPA,
  output [3:0] CASDOUTPB,
  output CASOUTDBITERR,
  output CASOUTSBITERR,
  output DBITERR,
  output [31:0] DOUTADOUT,
  output [31:0] DOUTBDOUT,
  output [3:0] DOUTPADOUTP,
  output [3:0] DOUTPBDOUTP,
  output [7:0] ECCPARITY,
  output [8:0] RDADDRECC,
  output SBITERR,
  input [14:0] ADDRARDADDR,
  input [14:0] ADDRBWRADDR,
  input ADDRENA,
  input ADDRENB,
  input CASDIMUXA,
  input CASDIMUXB,
  input [31:0] CASDINA,
  input [31:0] CASDINB,
  input [3:0] CASDINPA,
  input [3:0] CASDINPB,
  input CASDOMUXA,
  input CASDOMUXB,
  input CASDOMUXEN_A,
  input CASDOMUXEN_B,
  input CASINDBITERR,
  input CASINSBITERR,
  input CASOREGIMUXA,
  input CASOREGIMUXB,
  input CASOREGIMUXEN_A,
  input CASOREGIMUXEN_B,
  input CLKARDCLK,
  input CLKBWRCLK,
  input [31:0] DINADIN,
  input [31:0] DINBDIN,
  input [3:0] DINPADINP,
  input [3:0] DINPBDINP,
  input ECCPIPECE,
  input ENARDEN,
  input ENBWREN,
  input INJECTDBITERR,
  input INJECTSBITERR,
  input REGCEAREGCE,
  input REGCEB,
  input RSTRAMARSTRAM,
  input RSTRAMB,
  input RSTREGARSTREG,
  input RSTREGB,
  input SLEEP,
  input [3:0] WEA,
  input [7:0] WEBWE
);

  initial begin
    if (READ_WIDTH_A != 36 || READ_WIDTH_B != 36 || WRITE_WIDTH_A != 36 || WRITE_WIDTH_B != 36)
      $fatal(1, "RAMB36E2 %m: only READ_WIDTH = WRITE_WIDTH = 36 is modelled");
    if (CASCADE_ORDER_A != "NONE" || CASCADE_ORDER_B != "NONE" || CLOCK_DOMAINS != "COMMON" || INIT_FILE != "NONE")
      $fatal(1, "RAMB36E2 %m: cascade, INDEPENDENT clocks and INIT_FILE are not modelled");
    if (EN_ECC_READ != "FALSE" || EN_ECC_WRITE != "FALSE")
      $fatal(1, "RAMB36E2 %m: ECC is not modelled");
  end

  // 1024 words of 32 data + 4 parity bits; word w is INIT bits [32w+31:32w], INITP bits [4w+3:4w]
  reg [35:0] mem [0:1023];
  wire [32767:0] init = {INIT_7F, INIT_7E, INIT_7D, INIT_7C, INIT_7B, INIT_7A, INIT_79, INIT_78, INIT_77, INIT_76, INIT_75, INIT_74, INIT_73, INIT_72, INIT_71, INIT_70, INIT_6F, INIT_6E, INIT_6D, INIT_6C, INIT_6B, INIT_6A, INIT_69, INIT_68, INIT_67, INIT_66, INIT_65, INIT_64, INIT_63, INIT_62, INIT_61, INIT_60, INIT_5F, INIT_5E, INIT_5D, INIT_5C, INIT_5B, INIT_5A, INIT_59, INIT_58, INIT_57, INIT_56, INIT_55, INIT_54, INIT_53, INIT_52, INIT_51, INIT_50, INIT_4F, INIT_4E, INIT_4D, INIT_4C, INIT_4B, INIT_4A, INIT_49, INIT_48, INIT_47, INIT_46, INIT_45, INIT_44, INIT_43, INIT_42, INIT_41, INIT_40, INIT_3F, INIT_3E, INIT_3D, INIT_3C, INIT_3B, INIT_3A, INIT_39, INIT_38, INIT_37, INIT_36, INIT_35, INIT_34, INIT_33, INIT_32, INIT_31, INIT_30, INIT_2F, INIT_2E, INIT_2D, INIT_2C, INIT_2B, INIT_2A, INIT_29, INIT_28, INIT_27, INIT_26, INIT_25, INIT_24, INIT_23, INIT_22, INIT_21, INIT_20, INIT_1F, INIT_1E, INIT_1D, INIT_1C, INIT_1B, INIT_1A, INIT_19, INIT_18, INIT_17, INIT_16, INIT_15, INIT_14, INIT_13, INIT_12, INIT_11, INIT_10, INIT_0F, INIT_0E, INIT_0D, INIT_0C, INIT_0B, INIT_0A, INIT_09, INIT_08, INIT_07, INIT_06, INIT_05, INIT_04, INIT_03, INIT_02, INIT_01, INIT_00};
  wire [4095:0] initp = {INITP_0F, INITP_0E, INITP_0D, INITP_0C, INITP_0B, INITP_0A, INITP_09, INITP_08, INITP_07, INITP_06, INITP_05, INITP_04, INITP_03, INITP_02, INITP_01, INITP_00};
  integer k;
  initial for (k = 0; k < 1024; k = k + 1) mem[k] = {initp[4*k +: 4], init[32*k +: 32]};

  function automatic [35:0] bytes(input [3:0] we);   // lane i: data [8i+7:8i] and parity bit i
    integer b;
    bytes = 0;
    for (b = 0; b < 4; b = b + 1) if (we[b]) begin bytes[8 * b +: 8] = 8'hff; bytes[32 + b] = 1'b1; end
  endfunction

  wire en_a = ENARDEN ^ IS_ENARDEN_INVERTED, en_b = ENBWREN ^ IS_ENBWREN_INVERTED;
  wire rstram_a = RSTRAMARSTRAM ^ IS_RSTRAMARSTRAM_INVERTED, rstram_b = RSTRAMB ^ IS_RSTRAMB_INVERTED;
  wire rstreg_a = RSTREGARSTREG ^ IS_RSTREGARSTREG_INVERTED, rstreg_b = RSTREGB ^ IS_RSTREGB_INVERTED;
  wire [9:0] ad_a = ADDRARDADDR[14:5], ad_b = ADDRBWRADDR[14:5];
  wire [35:0] m_a = en_a ? bytes(WEA) : 36'h0, m_b = en_b ? bytes(WEBWE[3:0]) : 36'h0;
  wire [35:0] d_a = {DINPADINP, DINADIN}, d_b = {DINPBDINP, DINBDIN};
  wire [35:0] old_a = mem[ad_a], old_b = mem[ad_b];
  wire [35:0] new_a = d_a & m_a | old_a & ~m_a, new_b = d_b & m_b | old_b & ~m_b;
  wire both = |m_a && |m_b && ad_a == ad_b;                     // port A's bytes win
  reg [35:0] lat_a = INIT_A, lat_b = INIT_B, reg_a = INIT_A, reg_b = INIT_B;

  always @(posedge CLKARDCLK) begin
    if (en_a) begin
      if (rstram_a) lat_a <= SRVAL_A;
      else if (!(|m_a)) lat_a <= old_a;
      else if (WRITE_MODE_A == "WRITE_FIRST") lat_a <= new_a;
      else if (WRITE_MODE_A == "READ_FIRST") lat_a <= old_a;
    end
    if (rstreg_a && (RSTREG_PRIORITY_A == "RSTREG" || REGCEAREGCE)) reg_a <= SRVAL_A;
    else if (REGCEAREGCE) reg_a <= lat_a;
    if (en_b) begin
      if (rstram_b) lat_b <= SRVAL_B;
      else if (!(|m_b)) lat_b <= old_b;
      else if (WRITE_MODE_B == "WRITE_FIRST") lat_b <= both ? new_a & m_a | new_b & ~m_a : new_b;
      else if (WRITE_MODE_B == "READ_FIRST") lat_b <= old_b;
    end
    if (rstreg_b && (RSTREG_PRIORITY_B == "RSTREG" || REGCEB)) reg_b <= SRVAL_B;
    else if (REGCEB) reg_b <= lat_b;
    if (|m_b) mem[ad_b] <= both ? new_a & m_a | new_b & ~m_a : new_b;
    if (|m_a && !both) mem[ad_a] <= new_a;
  end

  wire [35:0] q_a = DOA_REG ? reg_a : lat_a, q_b = DOB_REG ? reg_b : lat_b;
  assign {DOUTPADOUTP, DOUTADOUT} = q_a;
  assign {DOUTPBDOUTP, DOUTBDOUT} = q_b;
  assign {CASDOUTPA, CASDOUTA} = q_a;
  assign {CASDOUTPB, CASDOUTB} = q_b;
  assign CASOUTDBITERR = 1'b0; assign CASOUTSBITERR = 1'b0; assign DBITERR = 1'b0; assign SBITERR = 1'b0;
  assign ECCPARITY = 8'h0; assign RDADDRECC = 9'h0;
endmodule
/* verilator lint_on UNUSEDPARAM */
/* verilator lint_on UNUSEDSIGNAL */
