`timescale 1 ps / 1 ps
// RAMB18E2: generated by gen_ramb.py (see there for what is modelled and how it was checked).
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off UNUSEDPARAM */
module RAMB18E2 #(
  parameter CASCADE_ORDER_A = "NONE",
  parameter CASCADE_ORDER_B = "NONE",
  parameter CLOCK_DOMAINS = "INDEPENDENT",
  parameter integer DOA_REG = 1,
  parameter integer DOB_REG = 1,
  parameter ENADDRENA = "FALSE",
  parameter ENADDRENB = "FALSE",
  parameter [255:0] INIT_00 = 256'h0,
  parameter [255:0] INIT_01 = 256'h0,
  parameter [255:0] INIT_02 = 256'h0,
  parameter [255:0] INIT_03 = 256'h0,
  parameter [255:0] INIT_04 = 256'h0,
  parameter [255:0] INIT_05 = 256'h0,
  parameter [255:0] INIT_06 = 256'h0,
  parameter [255:0] INIT_07 = 256'h0,
  parameter [255:0] INIT_08 = 256'h0,
  parameter [255:0] INIT_09 = 256'h0,
  parameter [255:0] INIT_0A = 256'h0,
  parameter [255:0] INIT_0B = 256'h0,
  parameter [255:0] INIT_0C = 256'h0,
  parameter [255:0] INIT_0D = 256'h0,
  parameter [255:0] INIT_0E = 256'h0,
  parameter [255:0] INIT_0F = 256'h0,
  parameter [255:0] INIT_10 = 256'h0,
  parameter [255:0] INIT_11 = 256'h0,
  parameter [255:0] INIT_12 = 256'h0,
  parameter [255:0] INIT_13 = 256'h0,
  parameter [255:0] INIT_14 = 256'h0,
  parameter [255:0] INIT_15 = 256'h0,
  parameter [255:0] INIT_16 = 256'h0,
  parameter [255:0] INIT_17 = 256'h0,
  parameter [255:0] INIT_18 = 256'h0,
  parameter [255:0] INIT_19 = 256'h0,
  parameter [255:0] INIT_1A = 256'h0,
  parameter [255:0] INIT_1B = 256'h0,
  parameter [255:0] INIT_1C = 256'h0,
  parameter [255:0] INIT_1D = 256'h0,
  parameter [255:0] INIT_1E = 256'h0,
  parameter [255:0] INIT_1F = 256'h0,
  parameter [255:0] INIT_20 = 256'h0,
  parameter [255:0] INIT_21 = 256'h0,
  parameter [255:0] INIT_22 = 256'h0,
  parameter [255:0] INIT_23 = 256'h0,
  parameter [255:0] INIT_24 = 256'h0,
  parameter [255:0] INIT_25 = 256'h0,
  parameter [255:0] INIT_26 = 256'h0,
  parameter [255:0] INIT_27 = 256'h0,
  parameter [255:0] INIT_28 = 256'h0,
  parameter [255:0] INIT_29 = 256'h0,
  parameter [255:0] INIT_2A = 256'h0,
  parameter [255:0] INIT_2B = 256'h0,
  parameter [255:0] INIT_2C = 256'h0,
  parameter [255:0] INIT_2D = 256'h0,
  parameter [255:0] INIT_2E = 256'h0,
  parameter [255:0] INIT_2F = 256'h0,
  parameter [255:0] INIT_30 = 256'h0,
  parameter [255:0] INIT_31 = 256'h0,
  parameter [255:0] INIT_32 = 256'h0,
  parameter [255:0] INIT_33 = 256'h0,
  parameter [255:0] INIT_34 = 256'h0,
  parameter [255:0] INIT_35 = 256'h0,
  parameter [255:0] INIT_36 = 256'h0,
  parameter [255:0] INIT_37 = 256'h0,
  parameter [255:0] INIT_38 = 256'h0,
  parameter [255:0] INIT_39 = 256'h0,
  parameter [255:0] INIT_3A = 256'h0,
  parameter [255:0] INIT_3B = 256'h0,
  parameter [255:0] INIT_3C = 256'h0,
  parameter [255:0] INIT_3D = 256'h0,
  parameter [255:0] INIT_3E = 256'h0,
  parameter [255:0] INIT_3F = 256'h0,
  parameter [255:0] INITP_00 = 256'h0,
  parameter [255:0] INITP_01 = 256'h0,
  parameter [255:0] INITP_02 = 256'h0,
  parameter [255:0] INITP_03 = 256'h0,
  parameter [255:0] INITP_04 = 256'h0,
  parameter [255:0] INITP_05 = 256'h0,
  parameter [255:0] INITP_06 = 256'h0,
  parameter [255:0] INITP_07 = 256'h0,
  parameter [17:0] INIT_A = 18'h0,
  parameter [17:0] INIT_B = 18'h0,
  parameter INIT_FILE = "NONE",
  parameter [0:0] IS_CLKARDCLK_INVERTED = 1'b0,
  parameter [0:0] IS_CLKBWRCLK_INVERTED = 1'b0,
  parameter [0:0] IS_ENARDEN_INVERTED = 1'b0,
  parameter [0:0] IS_ENBWREN_INVERTED = 1'b0,
  parameter [0:0] IS_RSTRAMARSTRAM_INVERTED = 1'b0,
  parameter [0:0] IS_RSTRAMB_INVERTED = 1'b0,
  parameter [0:0] IS_RSTREGARSTREG_INVERTED = 1'b0,
  parameter [0:0] IS_RSTREGB_INVERTED = 1'b0,
  parameter RDADDRCHANGEA = "FALSE",
  parameter RDADDRCHANGEB = "FALSE",
  parameter integer READ_WIDTH_A = 0,
  parameter integer READ_WIDTH_B = 0,
  parameter RSTREG_PRIORITY_A = "RSTREG",
  parameter RSTREG_PRIORITY_B = "RSTREG",
  parameter SIM_COLLISION_CHECK = "ALL",
  parameter SLEEP_ASYNC = "FALSE",
  parameter [17:0] SRVAL_A = 18'h0,
  parameter [17:0] SRVAL_B = 18'h0,
  parameter WRITE_MODE_A = "NO_CHANGE",
  parameter WRITE_MODE_B = "NO_CHANGE",
  parameter integer WRITE_WIDTH_A = 0,
  parameter integer WRITE_WIDTH_B = 0
)(
  output [15:0] CASDOUTA,
  output [15:0] CASDOUTB,
  output [1:0] CASDOUTPA,
  output [1:0] CASDOUTPB,
  output [15:0] DOUTADOUT,
  output [15:0] DOUTBDOUT,
  output [1:0] DOUTPADOUTP,
  output [1:0] DOUTPBDOUTP,
  input [13:0] ADDRARDADDR,
  input [13:0] ADDRBWRADDR,
  input ADDRENA,
  input ADDRENB,
  input CASDIMUXA,
  input CASDIMUXB,
  input [15:0] CASDINA,
  input [15:0] CASDINB,
  input [1:0] CASDINPA,
  input [1:0] CASDINPB,
  input CASDOMUXA,
  input CASDOMUXB,
  input CASDOMUXEN_A,
  input CASDOMUXEN_B,
  input CASOREGIMUXA,
  input CASOREGIMUXB,
  input CASOREGIMUXEN_A,
  input CASOREGIMUXEN_B,
  input CLKARDCLK,
  input CLKBWRCLK,
  input [15:0] DINADIN,
  input [15:0] DINBDIN,
  input [1:0] DINPADINP,
  input [1:0] DINPBDINP,
  input ENARDEN,
  input ENBWREN,
  input REGCEAREGCE,
  input REGCEB,
  input RSTRAMARSTRAM,
  input RSTRAMB,
  input RSTREGARSTREG,
  input RSTREGB,
  input SLEEP,
  input [1:0] WEA,
  input [3:0] WEBWE
);

  initial begin
    if (READ_WIDTH_A != 18 || READ_WIDTH_B != 18 || WRITE_WIDTH_A != 18 || WRITE_WIDTH_B != 18)
      $fatal(1, "RAMB18E2 %m: only READ_WIDTH = WRITE_WIDTH = 18 is modelled");
    if (CASCADE_ORDER_A != "NONE" || CASCADE_ORDER_B != "NONE" || CLOCK_DOMAINS != "COMMON" || INIT_FILE != "NONE")
      $fatal(1, "RAMB18E2 %m: cascade, INDEPENDENT clocks and INIT_FILE are not modelled");
  end

  // 1024 words of 16 data + 2 parity bits; word w is INIT bits [16w+15:16w], INITP bits [2w+1:2w]
  reg [17:0] mem [0:1023];
  wire [16383:0] init = {INIT_3F, INIT_3E, INIT_3D, INIT_3C, INIT_3B, INIT_3A, INIT_39, INIT_38, INIT_37, INIT_36, INIT_35, INIT_34, INIT_33, INIT_32, INIT_31, INIT_30, INIT_2F, INIT_2E, INIT_2D, INIT_2C, INIT_2B, INIT_2A, INIT_29, INIT_28, INIT_27, INIT_26, INIT_25, INIT_24, INIT_23, INIT_22, INIT_21, INIT_20, INIT_1F, INIT_1E, INIT_1D, INIT_1C, INIT_1B, INIT_1A, INIT_19, INIT_18, INIT_17, INIT_16, INIT_15, INIT_14, INIT_13, INIT_12, INIT_11, INIT_10, INIT_0F, INIT_0E, INIT_0D, INIT_0C, INIT_0B, INIT_0A, INIT_09, INIT_08, INIT_07, INIT_06, INIT_05, INIT_04, INIT_03, INIT_02, INIT_01, INIT_00};
  wire [2047:0] initp = {INITP_07, INITP_06, INITP_05, INITP_04, INITP_03, INITP_02, INITP_01, INITP_00};
  integer k;
  initial for (k = 0; k < 1024; k = k + 1) mem[k] = {initp[2*k +: 2], init[16*k +: 16]};

  function automatic [17:0] bytes(input [1:0] we);   // lane i: data [8i+7:8i] and parity bit i
    integer b;
    bytes = 0;
    for (b = 0; b < 2; b = b + 1) if (we[b]) begin bytes[8 * b +: 8] = 8'hff; bytes[16 + b] = 1'b1; end
  endfunction

  wire en_a = ENARDEN ^ IS_ENARDEN_INVERTED, en_b = ENBWREN ^ IS_ENBWREN_INVERTED;
  wire rstram_a = RSTRAMARSTRAM ^ IS_RSTRAMARSTRAM_INVERTED, rstram_b = RSTRAMB ^ IS_RSTRAMB_INVERTED;
  wire rstreg_a = RSTREGARSTREG ^ IS_RSTREGARSTREG_INVERTED, rstreg_b = RSTREGB ^ IS_RSTREGB_INVERTED;
  wire [9:0] ad_a = ADDRARDADDR[13:4], ad_b = ADDRBWRADDR[13:4];
  wire [17:0] m_a = en_a ? bytes(WEA) : 18'h0, m_b = en_b ? bytes(WEBWE[1:0]) : 18'h0;
  wire [17:0] d_a = {DINPADINP, DINADIN}, d_b = {DINPBDINP, DINBDIN};
  wire [17:0] old_a = mem[ad_a], old_b = mem[ad_b];
  wire [17:0] new_a = d_a & m_a | old_a & ~m_a, new_b = d_b & m_b | old_b & ~m_b;
  wire both = |m_a && |m_b && ad_a == ad_b;                     // port A's bytes win
  reg [17:0] lat_a = INIT_A, lat_b = INIT_B, reg_a = INIT_A, reg_b = INIT_B;

  always @(posedge CLKARDCLK) begin
    if (en_a) begin
      if (rstram_a) lat_a <= SRVAL_A;
      else if (!(|m_a)) lat_a <= old_a;
      else if (WRITE_MODE_A == "WRITE_FIRST") lat_a <= new_a;
      else if (WRITE_MODE_A == "READ_FIRST") lat_a <= old_a;
    end
    if (rstreg_a && (RSTREG_PRIORITY_A == "RSTREG" || REGCEAREGCE)) reg_a <= SRVAL_A;
    else if (REGCEAREGCE) reg_a <= lat_a;
    if (en_b) begin
      if (rstram_b) lat_b <= SRVAL_B;
      else if (!(|m_b)) lat_b <= old_b;
      else if (WRITE_MODE_B == "WRITE_FIRST") lat_b <= both ? new_a & m_a | new_b & ~m_a : new_b;
      else if (WRITE_MODE_B == "READ_FIRST") lat_b <= old_b;
    end
    if (rstreg_b && (RSTREG_PRIORITY_B == "RSTREG" || REGCEB)) reg_b <= SRVAL_B;
    else if (REGCEB) reg_b <= lat_b;
    if (|m_b) mem[ad_b] <= both ? new_a & m_a | new_b & ~m_a : new_b;
    if (|m_a && !both) mem[ad_a] <= new_a;
  end

  wire [17:0] q_a = DOA_REG ? reg_a : lat_a, q_b = DOB_REG ? reg_b : lat_b;
  assign {DOUTPADOUTP, DOUTADOUT} = q_a;
  assign {DOUTPBDOUTP, DOUTBDOUT} = q_b;
  assign {CASDOUTPA, CASDOUTA} = q_a;
  assign {CASDOUTPB, CASDOUTB} = q_b;
endmodule
/* verilator lint_on UNUSEDPARAM */
/* verilator lint_on UNUSEDSIGNAL */
