#!/bin/sh
# run.sh [workdir]: URAM288.v of this repository against Vivado's unisims URAM288 in xsim (Vivado on PATH).
# Each line: DEPTH (1 stand-alone, 2.. cascade) OREG_A OREG_B USE_EXT_CE_A USE_EXT_CE_B BWE_MODE REG_CAS RST%.
set -e
D=$(cd "$(dirname "$0")"; pwd); W=${1:-$D/work}; mkdir -p "$W"; cd "$W"
sed 's/^module URAM288 /module URAM288_MODEL /' "$D/../../URAM288.v" > model.v
xvlog -sv "$D/tb.sv" model.v "$XILINX_VIVADO/data/verilog/src/glbl.v" > xvlog.log
while read cfg; do
  set -- $cfg
  xelab -mt 2 -L unisims_ver tb glbl -s s -generic_top DEPTH=$1 -generic_top OREG_A=\"$2\" -generic_top OREG_B=\"$3\" \
    -generic_top EXT_A=\"$4\" -generic_top EXT_B=\"$5\" -generic_top BWE_MODE=\"$6\" -generic_top REG_CAS=\"$7\" \
    -generic_top RST_PCT=$8 > xelab.log
  xsim s -R | grep -E '^(PASS|FAIL|cycle| model)'
done <<CFGS
1 TRUE TRUE FALSE FALSE PARITY_INDEPENDENT FALSE 0
1 FALSE FALSE FALSE FALSE PARITY_INDEPENDENT FALSE 0
1 TRUE FALSE TRUE TRUE PARITY_INTERLEAVED FALSE 0
1 FALSE TRUE TRUE FALSE PARITY_INTERLEAVED FALSE 0
1 TRUE TRUE FALSE FALSE PARITY_INDEPENDENT FALSE 5
1 FALSE FALSE TRUE TRUE PARITY_INDEPENDENT FALSE 5
2 FALSE FALSE FALSE FALSE PARITY_INDEPENDENT FALSE 0
2 FALSE FALSE FALSE FALSE PARITY_INDEPENDENT FALSE 5
2 TRUE FALSE FALSE FALSE PARITY_INTERLEAVED FALSE 5
2 FALSE TRUE FALSE FALSE PARITY_INDEPENDENT TRUE 0
2 TRUE TRUE FALSE FALSE PARITY_INTERLEAVED TRUE 5
3 FALSE FALSE FALSE FALSE PARITY_INDEPENDENT FALSE 0
3 TRUE FALSE FALSE FALSE PARITY_INDEPENDENT FALSE 5
3 FALSE FALSE FALSE FALSE PARITY_INTERLEAVED TRUE 5
3 FALSE TRUE FALSE FALSE PARITY_INDEPENDENT TRUE 0
CFGS
